### ISSUE TITLE
Troubleshooting: a function for memory check

### ISSUE THREAD

**Issue by wukefe** [Sable/ostrich-suite#4]
The following function should work in a fresh node environment since `process` is a default module.

```shell
process.memoryUsed();
```

However, when I tried to use it in a benchmark `backprop`.  The system returned

```
TypeError: process.memoryUsed is not a function
```

Then, I went to check the temporary file in the folder `build`.  I could see the name `process` is used many times after the actual computation code.   I'm curious if the same names in the script caused the problem.   I'm not that proficient in JS, so I post the problem here to ask @elavoie for help.

**Comment by elavoie** [comment]
My node installation also has 'process.memoryUsage' but the JS code after having been packaged with browserify does not see that method (browserify is used to package the JS code). I tested in Firefox and Chrome and none of them expose a 'process' object so that must be why browserify does not expose that method.

I think using an OS tool to monitor the memory usage of the execution environment would be more robust and general than relying on a specific language implementation methods. How do you monitor memory usage for a native executable (compiled C code)?

**Comment by wukefe** [comment]
Hi @elavoie, I found a system (OS) tool to monitor the memory usage.   It was the `time` command (see the attached script `run_node` in the email for details).  To my surprise, this system function was able to measure the `maximum resident set size` which means the memory used for the entire tools, including wu-wei and its running benchmark.

**Comment by elavoie** [comment]
@wukefe ok good, could you close the issue if it fills your need? Thanks.

**Comment by wukefe** [comment]
Yes, closing .... closed!
